services:

  # Web
  web:
    build:
      context: ./.docker/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "5173:5173"
    restart: always
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel
      - redis_network

  # Redis
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    networks:
      - redis_network

  # mariadb:
  #   image: mariadb:10.6.17-focal
  #   restart: always
  #   environment:
  #     MARIADB_ROOT_PASSWORD: root
  #   ports:
  #     - "3306:3306"
  #   networks:
  #       - laravel

  # Database
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: 'laravel'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: 'laravel'
        MYSQL_USER: 'laravel'
        MYSQL_PASSWORD: 'laravel'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - 'db_data:/var/lib/mysql'
    networks:
        - laravel

networks:
  laravel:
  redis_network:

volumes:
  db_data: